<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>pers.meteor</groupId>
        <artifactId>meteor-module</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>meteor-module-system</artifactId>
    <packaging>pom</packaging>

    <description>meteor-module-system系统管理模块</description>

    <modules>
        <module>meteor-system-api</module>
    </modules>
</project>
