<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>pers.meteor</groupId>
        <artifactId>meteor-cloud-v2</artifactId>
        <version>1.0.0-snapshot</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>meteor-module-auth</module>
        <module>meteor-module-system</module>
        <module>meteor-module-gen</module>
        <module>meteor-module-job</module>
        <module>meteor-module-file</module>
        <module>meteor-module-pay</module>
        <module>meteor-module-member</module>
        <module>meteor-module-monitor</module>
    </modules>

    <artifactId>meteor-modules</artifactId>
    <packaging>pom</packaging>

    <description>
        meteor-cloud-module业务模块
    </description>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
    </dependencies>

</project>
