<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>pers.meteor</groupId>
        <artifactId>meteor-framework</artifactId>
        <version>1.0.0-snapshot</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>meteor-boot-starter-document</artifactId>

    <description>
        meteor-boot-starter-document
    </description>

	<dependencies>

        <!-- SpringBoot Web -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- Swagger -->
        <dependency>
            <groupId>org.springdoc</groupId> <!-- 接口文档 UI：默认 -->
            <artifactId>springdoc-openapi-ui</artifactId>
        </dependency>

	</dependencies>
</project>
