<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>pers.meteor</groupId>
    <artifactId>meteor-framework</artifactId>
    <packaging>pom</packaging>

    <name>meteor-framework</name>
    <version>${revision}</version>
    <description>meteor-common通用模块</description>

    <properties>
        <!-- 项目版本号 -->
        <revision>1.0.0-snapshot</revision>
    </properties>
    <modules>
        <module>meteor-common-dependencies</module>
        <module>meteor-common</module>
        <module>meteor-boot-starter-security</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>pers.meteor</groupId>
                <artifactId>meteor-common-dependencies</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
