<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>pers.meteor</groupId>
        <artifactId>meteor-module-shared</artifactId>
        <version>1.0.0-snapshot</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>meteor-shared-api</artifactId>
    <packaging>jar</packaging>

    <description>
        meteor-shared-api 共享服务接口
    </description>

    <dependencies>
        <dependency>
            <groupId>pers.meteor</groupId>
            <artifactId>meteor-common</artifactId>
        </dependency>

        <dependency>
            <groupId>pers.meteor</groupId>
            <artifactId>meteor-boot-starter-document</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- 参数校验 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- RPC 远程调用相关 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
